AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  lambda-nodejs20.x
  Sample SAM Template for lambda-nodejs20.x

Resources:
  #Roles
  RoleAppSyncLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allow-access-to-lambda-from-appsync
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !GetAtt GetBooksSortByGenderFunction.Arn

  RoleAppSyncDynamoDB:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${APIName}-dynamodb-policy
      ManagedPolicyArns:
        - !Ref PolicyDynamoDB
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com

  PolicyDynamoDB:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${BookManagementTable}

  BMUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: BMUserPool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  BMUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: BMAppClient
      UserPoolId: !Ref BMUserPool
      GenerateSecret: false
      RefreshTokenValidity: 30

  # FUNCTIONS----------------------------------------------------------------------------------------------------------------
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get all books
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getBooks/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetBookDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get book details
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getBookDetails/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  DeleteBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete books
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/deleteBooks/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetBooksSortByGenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get books order by gender
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getBooksSortByGender/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetAuthorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get all Authors
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getAuthors/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetAuthorDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get Author details
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getAuthorDetails/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  DeleteAuthorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete authors
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/deleteAuthors/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetGenresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get all Genres
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getGenres/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  GetGenreDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get Genre details
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/getGenreDetails/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  DeleteGenresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete Genres
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: functions/deleteGenres/build
      Timeout: 10
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookManagementTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BookManagementTable
          REGION: !Ref AWS::Region

  # SaveBookFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Description: Save book
  #     Runtime: go1.x
  #     Handler: SaveBook
  #     CodeUri: functions/SaveBook
  #     Timeout: 10
  #     MemorySize: 128
  #     Policies:
  #       - DynamoDBCrudPolicy:
  #           TableName: !Ref BookManagementTable
  #     Environment:
  #       Variables:
  #         TABLE_NAME: !Ref BookManagementTable

  # END FUNCTIONS----------------------------------------------------------------------------------------------------------------

  BMGraphQLAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaUri: schema.graphql
      Auth:
        Type: AMAZON_COGNITO_USER_POOLS
        UserPool:
          UserPoolId: !GetAtt BMUserPool.UserPoolId
          AwsRegion: !Sub ${AWS::Region}
          DefaultAction: ALLOW
      ApiKeys:
        BMApiKey:
          Description: BM api key
      DataSources:
        DynamoDb:
          BMDataSource:
            TableName: !Ref BookManagementTable
            TableArn: !GetAtt BookManagementTable.Arn
        Lambda:
          GetBooksAndGendersDataSource:
            FunctionArn: !GetAtt GetBooksSortByGenderFunction.Arn
            # ServiceRoleArn: !GetAtt RoleAppSyncLambda.Arn 
          GetBooksDataSource:
            FunctionArn: !GetAtt GetBooksFunction.Arn
          GetBookDetailsDataSource:
            FunctionArn: !GetAtt GetBookDetailsFunction.Arn
          DeleteBooksDataSource:
            FunctionArn: !GetAtt DeleteBooksFunction.Arn
          GetAuthorsDataSource:
            FunctionArn: !GetAtt GetAuthorsFunction.Arn
          GetAuthorDetailsDataSource:
            FunctionArn: !GetAtt GetAuthorDetailsFunction.Arn
          DeleteAuthorsDataSource:
            FunctionArn: !GetAtt DeleteAuthorsFunction.Arn
          GetGenresDataSource:
            FunctionArn: !GetAtt GetGenresFunction.Arn
          GetGenreDetailsDataSource:
            FunctionArn: !GetAtt GetGenreDetailsFunction.Arn
          DeleteGenresDataSource:
            FunctionArn: !GetAtt DeleteGenresFunction.Arn
      Functions:
        # Resolvers
        # Author
        listAuthorsInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetAuthorsDataSource
          CodeUri: gql/invoker.js
        getAuthorInfo:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetAuthorDetailsDataSource
          CodeUri: gql/invoker.js
        putAuthorInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/putAuthor.js
        deleteAuthorInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: DeleteAuthorsDataSource
          CodeUri: gql/invoker.js

        # Book
        listBooksInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetBooksDataSource
          CodeUri: gql/invoker.js
        getBookInfo:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetBookDetailsDataSource
          CodeUri: gql/invoker.js
        putBookInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/putBook.js
        deleteBookInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: DeleteBooksDataSource
          CodeUri: gql/invoker.js
        deleteBookRelationsInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/deleteBookRelations.js

        # Genre
        listGenresInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetGenresDataSource
          CodeUri: gql/invoker.js
        getGenreInfo:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetGenreDetailsDataSource
          CodeUri: gql/invoker.js
        putGenreInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/putGenre.js
        deleteGenreInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: DeleteGenresDataSource
          CodeUri: gql/invoker.js
        deleteGenreRelationsInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/deleteGenreRelations.js

        # Author and Books
        getAuthorBooksInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/getAuthorBooks.js

        getAuthorBooksMetadataInTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: BMDataSource
          CodeUri: resolvers/build/getAuthorBooksMetadata.js

        # Lambda invoker
        lambdaInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetBooksAndGendersDataSource
          CodeUri: gql/invoker.js

      Resolvers:
        Query:
          # Author
          getAuthor:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getAuthorInfo
          listAuthors:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - listAuthorsInTable

          # Book
          getBook:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getBookInfo
          listBooks:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - listBooksInTable

          # Author
          getGenre:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getGenreInfo
          listGenres:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - listGenresInTable

          # Author and Books
          getAuthorAndBooks:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - getAuthorBooksInTable
              - getAuthorBooksMetadataInTable

          # Lambdas function
          # Books and Genre
          listBooksSortByGenders:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - lambdaInvoker

        Mutation:
          # Author
          putAuthor:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - putAuthorInTable
          deleteAuthors:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - deleteAuthorInTable

          # Book
          putBook:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - putBookInTable
          deleteBooks:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - deleteBookInTable

          # Genre
          putGenre:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - putGenreInTable
          deleteGenres:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - deleteGenreInTable

  BookManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BookManagementTable
      KeySchema:
        - AttributeName: PK
          KeyType: HASH # Clave de partición
        - AttributeName: SK
          KeyType: RANGE # Clave de ordenación
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S # Tipo de atributo: String
        - AttributeName: SK
          AttributeType: S # Tipo de atributo: String
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: InverseIndex
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Parameters:
  APIName:
    Type: String
    Default: bm-epac-api

Outputs:
  BMGraphQLAPI:
    Description: AppSync API
    Value: !GetAtt BMGraphQLAPI.GraphQLUrl
  BMGraphQLAPIBMApiKey:
    Description: AppSync API Key
    Value: !GetAtt BMGraphQLAPIBMApiKey.ApiKey
  UserPoolId:
    Description: User Pool ID
    Value: !Ref BMUserPool
  UserPoolClientId:
    Description: User Pool Client ID
    Value: !Ref BMUserPoolClient
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
  AccountId:
    Description: AWS Account ID
    Value: !Ref AWS::AccountId