projects:
  Codegen Project:
    schemaPath: ../schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/models/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/models/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: none
        maxDepth: 2
extensions:
  amplify:
    version: 3
